### ISSUE TITLE
do not invite random people to join your org

### ISSUE THREAD

**Issue by steveoh** [EpicGames/ThirdParty#1]
thanks.

**Comment by renniejacob** [comment]
Ok

**Comment by Gingi006** [comment]
No problem

**Comment by razercortex101** [comment]
Ok

**Comment by manticstingray** [comment]
Ok

**Comment by paddy** [comment]
Yes, I also received an out-of-context invite, and am unsure why this happened.  It oddly coincides with me submitting a detailed bug report related to the Epic Games Launcher application in Windows.  Part of me wondered whether you thought I should fix it for you...  I'm happy to be invited to something, but an introduction message and a reason for invite would be appreciated.

**Comment by MxttyX** [comment]
Ok

**Comment by manticstingray** [comment]
Ok

**Comment by Dandroid87** [comment]
Gotcha

**Comment by Houlik** [comment]
K

**Comment by somaq6r** [comment]
Ok

**Comment by smashgamerr** [comment]
Ok

**Comment by razercortex101** [comment]
Please close this issue.

**Comment by Aserrag** [comment]
Sure
