### ISSUE TITLE
Double pump

### ISSUE THREAD

**Issue by RAILSURF** [EpicGames/ThirdParty#4]

**Comment by Anthonyhubgit** [comment]
Idk if we can sorry

**Comment by XorGentlem4n** [comment]
Sir, this is not the right place to post about your suggestion. [https://www.epicgames.com/fortnite/forums/suggestions-advice](url)

**Comment by EnterNewName** [comment]
BRING BACK DOUBLE PUMP

**Comment by billygoatj** [comment]
I don’t we can do that it has to wait to wait sir

**Comment by jwroth7** [comment]
Fake epic employee

**Comment by Anthonyhubgit** [comment]
Boy be quiet and sit down or I will leak all your info

**Comment by Anthonyhubgit** [comment]
Or I'll ban u like I banned tfue and Landon and prestonplays

**Comment by EnterNewName** [comment]
Like to see you try little kid

**Comment by Anthonyhubgit** [comment]
Damn it you caught me idk why I signed up for this site I don't use it or
even go on it

**Comment by RAILSURF** [comment]
I deleted the post

**Comment by Anthonyhubgit** [comment]
Hey,

I just signed the petition "Rename Fire Ants to Spicy Boys" and wanted to
see if you could help by adding your name.

Our goal is to reach 150,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/xzf94fYxDy

Thanks!
Anthony

**Comment by Thomas0899** [comment]
Working on something big. I’ve got 4 developers at work as we speak, *double pump will return*
