### ISSUE TITLE
How to download unreal engine on ubuntu?

### ISSUE THREAD

**Issue by OrfDaBeast** [EpicGames/ThirdParty#5]
I have made an account at github and epic games. were do i find unreal engine?

**Comment by Narven** [comment]
Please follow this link: [https://wiki.unrealengine.com/Building_On_Linux](https://wiki.unrealengine.com/Building_On_Linux)

It worked for me. But dont forget that you will not have access to the Epic Launcher which means you will not have access to anything in the marketplace

**Comment by OrfDaBeast** [comment]
thanks it worked!
