### ISSUE TITLE
Join the organization. 

### ISSUE THREAD

**Issue by stepfencurryxiao** [EpicGames/ThirdParty#8]
Hello, I am a student, I am very interested in programming, especially game development and machine learning, I would like to join your organization very much.
If you think I'm not the right person for you, you can refuse my request.
email: m18824909883@163.com

**Comment by OrfDaBeast** [comment]
Bro lol sup. It’s Orf. It’s a small world.

**Comment by OrfDaBeast** [comment]
Never mind wrong person

**Comment by Arshiamidos** [comment]
hi , i want join group too
sorry for issue , but this repo has issue tracking and i can right my will.   
i want join group and send email to epicgames, they said this repo has different adminstrator :(. 
can you add me ?  
thanks

**Comment by stepfencurryxiao** [comment]
Hi, @Arshiamidos . I have not received the invitation, I don't know if it agrees with my request, so I reopen this issue.

**Comment by stepfencurryxiao** [comment]
Hi @Arshiamidos . I have not received an invitation.

**Comment by stepfencurryxiao** [comment]
Hey @Arshiamidos . Have you received the results? If you receive it, I'll close the issue.

**Comment by Arshiamidos** [comment]
no not received !!
are you join?
